- name: Docker 文件
  href: index.md
- name: 快速入門
  expanded: true
  items:
    - name: Docker Marketplace 範本
      href: 'https://azuremarketplace.microsoft.com/en-us/marketplace/apps/CanonicalandMSOpenTech.DockerOnUbuntuServer1404LTS'
- name: 教學課程
  items:
    - name: 搭配 Docker 和 PostgreSQL 的 Python Web App
      href: ../app-service/containers/tutorial-python-postgresql-app.md?toc=%2fazure%2fpostgresql%2ftoc.json
    - name: 搭配 Docker Swarm 和 Azure DevOps 的 CI/CD
      href: /azure/container-service/container-service-docker-swarm-mode-setup-ci-cd-acs-engine
    - name: 搭配 Docker、Jenkins 和 Linux 的 CI/CD
      href: /azure/virtual-machines/linux/tutorial-jenkins-github-docker-cicd
- name: 使用說明指南
  items:
    - name: Docker VM 擴充功能
      href: /azure/virtual-machines/linux/dockerextension
    - name: Docker 機器
      href: /azure/virtual-machines/linux/docker-machine
    - name: Docker 容器登錄
      href: /azure/container-registry/container-registry-get-started-portal
- name: 資源
  items:
    - name: Azure 藍圖
      href: 'https://azure.microsoft.com/roadmap/'
    - name: Docker Azure 驅動程式
      href: 'https://docs.docker.com/machine/drivers/azure/'
    - name: Docker Azure 網站
      href: 'https://www.docker.com/docker-azure'
    - name: Docker 網站
      href: 'https://docker.com'