### YamlMime:YamlDocument
documentType: LandingData
title: Azure 文件中對 Ansible 的說明
metadata:
  title: Azure 文件中對 Ansible 的說明 - 教學課程、範例、參考和資源
  meta.description: Learn how to use Ansible to automate cloud provisioning, configuration management, and application deployments.
  services: terraform
  author: tomarcher
  manager: routlaw
  ms.service: ansible
  ms.tgt_pltfrm: na
  ms.devlang: devops
  ms.topic: landing-page
  ms.date: 07/05/2018
  ms.author: tarcher
  ms.openlocfilehash: 3d885c6374530884e761ecbee837d6406dd3e894
  ms.sourcegitcommit: ab3b2482704758ed13cccafcf24345e833ceaff3
  ms.translationtype: HT
  ms.contentlocale: zh-TW
  ms.lasthandoff: 07/06/2018
  ms.locfileid: "37868599"
abstract:
  description: 使用 <a href="http://www.ansible.com">Ansible</a> 自動佈建雲端、進行組態管理和應用程式部署。
sections:
- title: 5 分鐘快速入門
  items:
  - type: paragraph
    text: 設定 Ansible，並用它在 Azure 中建立 Linux 虛擬機器。
  - type: list
    style: icon48
    items:
    - image:
        src: /azure/media/index/azure_dev-9.svg
      text: 設定 Ansible
      href: /azure/virtual-machines/linux/ansible-install-configure?toc=%2Fen-us%2Fazure%2Fansible%2Ftoc.json&bc=%2Fen-us%2Fazure%2Fbread%2Ftoc.json
    - image:
        src: /azure/media/index/VirtualMachine.svg
      text: 建立 Linux VM
      href: /azure/virtual-machines/linux/ansible-create-vm?toc=%2Fen-us%2Fazure%2Fansible%2Ftoc.json&bc=%2Fen-us%2Fazure%2Fbread%2Ftoc.json
- title: 逐步教學課程
  items:
  - type: paragraph
    text: 了解如何使用 Ansible 建立和管理 Azure 計算和網路基礎結構。
  - type: list
    style: unordered
    items:
    - html: <a href="/azure/virtual-machines/linux/ansible-create-complete-vm?toc=%2Fen-us%2Fazure%2Fansible%2Ftoc.json&bc=%2Fen-us%2Fazure%2Fbread%2Ftoc.json">建立 Linux 虛擬機器，包括虛擬網路、公用 IP 位址以及虛擬網路介面卡。</a>
    - html: <a href="./ansible-run-playbook-in-cloudshell">連線至 Azure 虛擬機器並在 Cloud Shell 中執行 Ansible 腳本。</a>
    - html: <a href="./ansible-manage-azure-dynamic-inventories">建立和管理 Azure 資源的動態清查。</a>
- title: 參考
  items:
  - type: list
    style: cards
    className: cardsD
    items:
    - title: 腳本角色
      html: <p><a href="https://galaxy.ansible.com/Azure/azure_preview_modules/">azure_preview_module</a></p>
    - title: 版本與功能
      html: <p><a href="./ansible-matrix.md">模組和角色功能矩陣</a></p>
    - title: 工具
      html: <p><a href="https://marketplace.visualstudio.com/items?itemName=vscoss.vscode-ansible">適用於 Ansible 的 Visual Studio Code 擴充功能</a></p>
