- name: Ansible on Azure 文件
  href: ./index.yml
- name: 概觀
  items:
    - name: 關於 Ansible on Azure
      href: ./ansible-overview.md
- name: 快速入門
  expanded: true
  items:
    - name: 將 Ansible 解決方案範本部署至 CentOS
      href: ./ansible-deploy-solution-template.md
    - name: 在 Linux 虛擬機器上安裝 Ansible
      href: /azure/virtual-machines/linux/ansible-install-configure
      maintainContext: true
    - name: 在 Cloud Shell 中執行劇本
      href: ./ansible-run-playbook-in-cloudshell.md
    - name: 使用 Linux 虛擬機器
      expanded: true
      items:
        - name: 設定 Linux 虛擬機器
          href: /azure/virtual-machines/linux/ansible-create-vm
          maintainContext: true
        - name: 管理 Linux 虛擬機器
          href: /azure/virtual-machines/linux/ansible-manage-linux-vm
          maintainContext: true
- name: 教學課程
  items:
    - name: Azure 應用程式閘道
      items:
        - name: 管理網路流量
          href: ./ansible-create-configure-application-gateway.md
    - name: Azure App Service
      items:
        - name: 設定應用程式
          href: ./ansible-create-configure-azure-web-apps.md
        - name: 調整應用程式規模
          href: ./ansible-scale-azure-web-apps.md
    - name: Azure DevTest Labs
      items:
        - name: 設定實驗室
          href: ./ansible-devtest-labs-configure.md
    - name: Azure Kubernetes Service (AKS)
      items:
        - name: 設定 AKS 叢集
          href: ./ansible-create-configure-aks.md
        - name: 設定 Azure CNI 網路
          href: ./ansible-aks-configure-cni-networking.md
        - name: 設定 Kubenet 網路
          href: ./ansible-aks-configure-kubenet-networking.md
        - name: 在 AKS 叢集 中設定 RBAC 角色
          href: ./ansible-aks-configure-rbac.md
    - name: Azure HDInsight
      items:
        - name: 設定叢集
          href: ./ansible-azure-hdinsight-configure.md
    - name: Azure 服務匯流排
      items:
        - name: 設定佇列
          href: ./ansible-service-bus-queue-configure.md
        - name: 設定主題
          href: ./ansible-service-bus-topic-configure.md
    - name: 資料庫
      items:
        - name: 設定適用於 MySQL 的 Azure 資料庫
          href: ./ansible-create-configure-mysql.md
        - name: 設定 Azure Cosmos DB 帳戶
          href: ./ansible-data-cosmos-configure.md
        - name: 設定適用於 Redis 的 Azure 快取
          href: ./ansible-data-cache-for-redis-configure.md
    - name: 動態清查
      items:
        - name: 管理您的 Azure 資源
          href: ./ansible-manage-azure-dynamic-inventories.md
    - name: 虛擬機器擴展集
      items:
        - name: 設定
          href: ./ansible-create-configure-vmss.md
        - name: 部署
          href: ./ansible-deploy-app-vmss.md
        - name: Autoscale
          href: ./ansible-auto-scale-vmss.md
        - name: 更新自訂影像
          href: ./ansible-vmss-update-image.md
    - name: 虛擬網路
      items:
        - name: 設定對等互連
          href: ./ansible-vnet-peering-configure.md
        - name: 設定路由資料表
          href: ./ansible-create-configure-route-table.md
- name: 範例
  items:
    - name: 適用於 Azure 的 Ansible 實驗室
      href: 'https://github.com/microsoft/ansiblelabs'
    - name: Ansible Azure 劇本範例
      href: 'https://github.com/Azure-Samples/ansible-playbooks'
- name: 參考
  items:
    - name: 腳本角色
      items:
        - name: azure_module
          href: 'https://galaxy.ansible.com/Azure/azure_modules/'
        - name: azure_preview_module
          href: 'https://galaxy.ansible.com/Azure/azure_preview_modules'
    - name: 版本與功能
      href: ./ansible-matrix.md
    - name: Azure 的所有模組
      href: 'https://docs.ansible.com/ansible/latest/modules/list_of_cloud_modules#azure'
- name: 工具
  items:
    - name: 適用於 Ansible 的 Visual Studio Code 擴充功能
      href: 'https://marketplace.visualstudio.com/items?itemName=vscoss.vscode-ansible'